import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/closebrackets',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/comment',
		'@codemirror/fold',
		'@codemirror/gutter',
		'@codemirror/highlight',
		'@codemirror/history',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/matchbrackets',
		'@codemirror/panel',
		'@codemirror/rangeset',
		'@codemirror/rectangular-selection',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/stream-parser',
		'@codemirror/text',
		'@codemirror/tooltip',
		'@codemirror/view',
		...builtins],
	format: 'cjs',
	target: 'es2016',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
});

// `production` builds main.js once and stops. Without it the build stays up and
// writes main.js again on every save, which is what `npm run dev` is for: a
// build that ended the moment it was run left the plugin folder holding
// whatever the last manual build wrote, and nothing said so.
if (prod) {
	try {
		await context.rebuild();
		console.log("Built main.js.");
	} catch {
		process.exit(1);
	} finally {
		await context.dispose();
	}
} else {
	await context.watch();
	console.log("Watching for changes. Reload the plugin in Obsidian to pick each build up.");
}
